
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilers;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int CHAR_CONST = 43;
  public static final int LGPAR = 14;
  public static final int CHAR = 9;
  public static final int GE = 29;
  public static final int UMINUS = 36;
  public static final int DOUBLE_CONST = 42;
  public static final int DOUBLE = 7;
  public static final int SEMI = 4;
  public static final int INT = 5;
  public static final int OUT = 38;
  public static final int MINUS = 19;
  public static final int WRITE = 17;
  public static final int INOUT = 39;
  public static final int NOT = 33;
  public static final int AND = 34;
  public static final int LT = 30;
  public static final int RPAR = 13;
  public static final int IN = 37;
  public static final int OR = 35;
  public static final int BOOL = 6;
  public static final int RGPAR = 15;
  public static final int COMMA = 10;
  public static final int DIV = 21;
  public static final int PLUS = 18;
  public static final int ASSIGN = 22;
  public static final int IF = 23;
  public static final int ID = 40;
  public static final int LE = 31;
  public static final int EOF = 0;
  public static final int TRUE = 45;
  public static final int INT_CONST = 41;
  public static final int error = 1;
  public static final int START = 3;
  public static final int EQ = 32;
  public static final int HEAD = 2;
  public static final int TIMES = 20;
  public static final int ELSE = 27;
  public static final int READ = 16;
  public static final int WHILE = 25;
  public static final int THEN = 24;
  public static final int LPAR = 12;
  public static final int STRING = 8;
  public static final int DEF = 11;
  public static final int FALSE = 46;
  public static final int STRING_CONST = 44;
  public static final int GT = 28;
  public static final int DO = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HEAD",
  "START",
  "SEMI",
  "INT",
  "BOOL",
  "DOUBLE",
  "STRING",
  "CHAR",
  "COMMA",
  "DEF",
  "LPAR",
  "RPAR",
  "LGPAR",
  "RGPAR",
  "READ",
  "WRITE",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "ASSIGN",
  "IF",
  "THEN",
  "WHILE",
  "DO",
  "ELSE",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NOT",
  "AND",
  "OR",
  "UMINUS",
  "IN",
  "OUT",
  "INOUT",
  "ID",
  "INT_CONST",
  "DOUBLE_CONST",
  "CHAR_CONST",
  "STRING_CONST",
  "TRUE",
  "FALSE"
  };
}

